on:
  push:
    branches:
      - main  # Runs on pushes to the main branch; change if your default branch has a different name
    paths:
      - 'src/nmr_schema/nmr_schema.yaml'  # Only trigger when the YAML file changes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Set up Python 3.x for LinkML

    - name: Install LinkML
      run: pip install linkml  # Install LinkML

    - name: Generate JSON Schema
      run: |
        gen-json-schema --closed src/nmr_schema/nmr_schema.yaml  >nmr.schema.json  # Generate JSON schema

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './'  # Directory containing files to publish
        publish_branch: gh-pages  # Assumes you're using a branch named gh-pages
        keep_files: true  # Set to false if you want a clean deploy each time
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy JSON schema to GitHub Pages'
